all:
  hosts:
    ansible3:
      ansible_host: a.b.c.d
      ansible_port: 22
      ansible_user: ubuntu

      ### Secrets env vars ######################################
      _go_secrets: "{{ lookup('file', '/keybase/team/epfl_idevfsd/ansible-formation/infra_test/secrets.yml') | from_yaml }}"


