---
- tags: all
  include_vars: setup-vars.yml


- name: Ajoute toutes les clefs ssh de la FSD
  ansible.builtin.shell:
    cmd: curl https://raw.githubusercontent.com/zuzu59/deploy-proxmox/master/get_ssh_key_fsd.sh | bash
    chdir: /home/ubuntu
  tags: [ never, init_ssh ]


- name: install useful packages
  apt:
    name:
      - htop
      - tree
    state: present
    force_apt_get: yes
  become: yes
  tags:
    - install_packages
    

- name: Copié le fichier toto.txt
  ansible.builtin.copy:
    src: ./toto.txt
    dest: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    mode: '0644'
    

- name: Création du dossier toto-dir
  ansible.builtin.file:
    path: "{{ toto_dir }}"
    state: directory
    mode: '0755'

- name: Création du dossier tutu-dir
  ansible.builtin.file:
    path: "{{ tutu_dir }}"
    state: directory
    mode: '0755'


# - include_tasks:
#     file: sativa-satosa.yml
#     apply:
#       tags: sativa
#   tags:
#     - sativa
#     - sativa.satosa.restart
# 
# - pause:
#     prompt: |
#       *******************************************************
#       * SATOSA backend → Tequila cryptographic introduction *
#       *******************************************************
# 
#       Please ensure that the {{ inventory_environment }} Tequila knows about
#       the SATOSA IdP-side (“backend”) identity, available at
#       https://{{ sativa_server_hostname }}/Sativa/proxy_saml2_backend.xml
# 
#       Please ensure also that the {{ inventory_environment }} Ivalua knows about
#       the SATOSA SP-side (“frontend”) identity, available at
#       https://{{ sativa_server_hostname }}/SAML-of-Catalyse/proxy.xml
# 
#       This is a manual step. Press Enter when done...
# 
#   tags:
#     - sativa
